//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceServiceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceInfo
    {
        public Nullable<int> CompanyID { get; set; }
        public string InvoiceID { get; set; }
        public Nullable<int> DateID { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string CustomerID { get; set; }
        public string ShippingAddress { get; set; }
    
        public virtual CompanyInfo CompanyInfo { get; set; }
    }
}
